import express from 'express';
import rutasUsuarios from './usuarios/rutas.usuarios.js';
import rutasEmpresas from './empresas/rutas.empresas.js';
import rutasSucursales from './sucursales/rutas.sucursales.js';
import rutasProductos from './productos/rutas.productos.js';
import rutasProveedores from './proveedores/rutas.proveedores.js';
import rutasClientes from './clientes/rutas.clientes.js';
import rutasAsignacionesCaja from './asignaciones_caja/rutas.asignaciones_caja.js';
import rutasCajas from './cajas/rutas.cajas.js';
import rutasAuditTrails from './audit_trails/rutas.audit_trails.js';
import rutasCategorias from './categorias/rutas.categorias.js';
import rutasStocks from './stocks/rutas.stocks.js';
import rutasSerializacionesComprobante from './serializaciones_comprobante/rutas.serializaciones_comprobante.js';
import rutasTiposComprobante from './tipos_comprobante/rutas.tipos_comprobante.js';
import rutasAlmacenes from './almacenes/rutas.almacenes.js';
import rutasImpresoras from './impresoras/rutas.impresoras.js';
import rutasMetodosPago from './metodos_pago/rutas.metodos_pago.js';
import rutasRoles from './roles/rutas.roles.js';
import rutasPermisos from './permisos/rutas.permisos.js';
import rutasModulos from './modulos/rutas.modulos.js';

const router = express.Router();

router.use('/usuarios', rutasUsuarios);
router.use('/empresas', rutasEmpresas);
router.use('/sucursales', rutasSucursales);
router.use('/productos', rutasProductos);
router.use('/proveedores', rutasProveedores);
router.use('/clientes', rutasClientes);
router.use('/asignaciones-caja', rutasAsignacionesCaja);
router.use('/cajas', rutasCajas);
router.use('/audit-trails', rutasAuditTrails);
router.use('/categorias', rutasCategorias);
router.use('/stocks', rutasStocks);
router.use('/serializaciones-comprobante', rutasSerializacionesComprobante);
router.use('/tipos-comprobante', rutasTiposComprobante);
router.use('/almacenes', rutasAlmacenes);
router.use('/impresoras', rutasImpresoras);
router.use('/metodos-pago', rutasMetodosPago);
router.use('/roles', rutasRoles);
router.use('/permisos', rutasPermisos);
router.use('/modulos', rutasModulos);

export default router;